// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyvcabctxplmkesocbvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5dmNhYmN0eHBsbWtlc29jYnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjIzOTMsImV4cCI6MjA2MjYzODM5M30.mYfNSm4dkudjKWyDTidxSQiNqJnykllfTkXhtbzVM9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);